name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    name: Generate Snake Contributions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Techyshubhs  # Replace with your GitHub username
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Ensure dist Directory Exists
        run: mkdir -p dist  # Ensures the dist folder exists before pushing

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output  # Output branch where snake animations will be stored
          build_dir: dist  # Directory containing the generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses default GitHub token
