name: Generate Snake

on:
  schedule: # Runs every week
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate Snake Animation (Light & Dark Mode)
      - name: Generate Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: Its-Shinde4241
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Upload to GitHub Pages
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
