name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Fix: Required before running the workflow

      - name: Generate Snake Animation (Dark Mode)
        uses: Platane/snk@v2
        with:
          github_user_name: Techyshubhs  # Ensure your username is correct
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg  # Fix: Removed query parameter

      - name: Deploy Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages  # Fix: Use gh-pages instead of 'output'
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Fix: Use a Personal Access Token
