name: 🐍 Generate Dark Mode Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Generate Dark Mode Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake-dark.svg
          color_snake: "#00FF00"   # Neon Green Snake
          color_dots: "#FFFFFF"    # White Dots
          color_empty: "#222222"   # Dark Background

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: snake-animation-dark
          path: dist/snake-dark.svg
          retention-days: 7  # Keeps artifacts for 7 days

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
